# azure-pipelines.yml

trigger:
  - master

pool:
  #vmImage: 'ubuntu-latest'  # You can use 'windows-latest' if preferred
name: 'DESKTOP-U6UTH74'
variables:
  # Define any additional variables here
  NODE_VERSION: '18.x'  # Specify the Node.js version you need

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install NPM Dependencies'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(Pipeline.Workspace)/.npm
    displayName: 'Cache NPM Modules'

  - script: |
      npx wdio run wdio.conf.js
    env:
      BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
      BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
    displayName: 'Run WebdriverIO Tests'
