# azure-pipelines.yml

trigger:
  - master

pool: Default
variables:
  # Define any additional variables here
  NODE_VERSION: '18.x'  # Specify the Node.js version you need

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'Install NPM Dependencies'
  - script: |
      npx wdio run wdio.conf.js
    env:
      BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
      BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
    displayName: 'Run WebdriverIO Tests'
  - script: |
      echo "Listing test-results folder contents:"
      dir test-results
    displayName: 'list test result directoty'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      testResultsFormat: 'JUnit'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: 'WebdriverIO JUnit Tests'
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'









